version: 2

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout

      - restore_cache:
          name: Restore Cache
          key: modules-rev1-{{ checksum "yarn.lock" }}

      - run:
          name: Install deps
          command: yarn install --frozen-lockfile

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Show coverage
          command: ls -la coverage

      - run:
          name: Upload coverage report
          command: yarn codecov

      - save_cache:
          name: Save Cache
          key: modules-rev1-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - persist_to_workspace:
          root: .
          paths: .

  publish:
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          at: .

      - add_ssh_keys:
          fingerprints:
            - "ec:65:03:d0:17:96:7d:78:1a:c2:0c:f5:94:16:53:6fY"

      - run:
          name: show contents
          command: ls -la

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run:
          name: Publish package
          command: yarn publish

      - run:
          name: Make sure we can push the release tag
          command: |

      - run:
          name: Tag the release
          command: |
            echo "Release v$(yarn -s pkgver) -- $(git show -s --format='%an <%ae>')"
            mkdir -p ~/.ssh
            echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            cat ~/.ssh/config
            yarn tag:release
            yarn tag:push


workflows:
  version: 2
  main:
    jobs:
      - build

      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
