version: 2

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout

      - restore_cache:
          name: Restore Cache
          key: modules-rev1-{{ checksum "yarn.lock" }}

      - run:
          name: Install deps
          command: yarn install --frozen-lockfile

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Show coverage
          command: ls -la coverage

      - run:
          name: Upload coverage report
          command: yarn codecov

      - save_cache:
          name: Save Cache
          key: modules-rev1-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - persist_to_workspace:
          root: .
          paths: .

  publish:
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          at: .

      - run:
          name: show contents
          command: ls -la

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run:
          name: Publish package
          command: yarn publish

      - run:
          name: Tag the release
          command: |
            echo "Release v$(yarn -s pkgver) -- $(git show -s --format='%an <%ae>')"
            yarn tag:release
            git tag -d $(yarn -s pkgver)
            git push origin $(yarn -s pkgver)


workflows:
  version: 2
  main:
    jobs:
      - build

      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
